### ISSUE TITLE
What if I only want to run classpath verification?

### ISSUE THREAD

**Issue by jeffalder** [newrelic/newrelic-gradle-verify-instrumentation#20]
## Summary

The plugin will generate tasks for every version that it finds in the range. However:
* If there's one version of the library
* It's not on Maven
* I have it copied locally

Then the plugin will not generate tasks.

## Desired Behavior

For the summary above, `verifyInstrumentation` should automatically generate and run the classpath task unless `verifyClasspath` is false. No further configuration should be required - particularly no `passes` or `passesOnly`.

**Comment by XiXiaPdx** [comment]
I think this is what you mean - https://github.com/newrelic/newrelic-gradle-verify-instrumentation/pull/21

**Comment by kford-newrelic** [comment]
Not prioritized for the product roadmap. Closing with no further action.
